#Web Server properties
server:
    port: 80

# https Configuration
keystorefile: keystore.p12
keystorepass: maplelabs
sslport: 443



#Spring properties
spring:
  datasource:
    serverName: http://localhost
    driverClassName: org.postgresql.Driver
    databaseName: acisizer
    url: jdbc:postgresql://localhost:5432/acisizer
    user: postgres
    password: postgres
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    cachePrepStmts: true
    useServerPrepStmts: true
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    poolName: ACISizerConnectionPool
    maximumPoolSize: 50
    minimumIdle: 6
    connectionTimeout: 30000
    idleTimeout: 30000


  jpa:
    show-sql : false
    properties: 
      hibernate.current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext

    
cisco: 
  remote:
    directory: /sizer/acitool/
    fileName: input_json.json

logging:
  level:
    org.hibernate : DEBUG

acisizer:
  security:
    jwt:
      issuer: admin   
      secret: acisizer
      ttlMillis: 60000000
      token: token
  plugin: 
    path: /
    file: predefinedApplicationPauloAlto.xml    
    jar:  palo_plugin-1.0.jar
