#Web Server properties
server:
    port: 8080

#https Configuration
keystorefile: keystore.p12
keystorepass: maplelabs
sslport: 8443

#Spring properties
spring:
  datasource:
    serverName: http://localhost
    driverClassName: org.postgresql.Driver
    databaseName: acisizer
    url: jdbc:postgresql://localhost:5432/acisizer
    user: postgres
    password: postgres
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    cachePrepStmts: true
    useServerPrepStmts: true
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    poolName: ACISizerConnectionPool
    maximumPoolSize: 50
    minimumIdle: 6
    connectionTimeout: 30000
    idleTimeout: 30000
    
  jpa:
    show-sql : true
    properties: 
      hibernate.current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
    
    
 #cisco tool properties
cisco: 
  remote:
    host: 1.1.1.1
    userName: user
    password: password
    directory: /home/sizer/acitool/


logging:
  file: my.log
  level:
    org.hibernate : DEBUG
 
acisizer:
  security:
    jwt:
      issuer: admin   
      secret: acisizer
      ttlMillis: 6000000
      token: token
      
  plugin: 
    path: 
    file: predefinedApplicationPauloAlto.xml
    jar: paloPlugin-0.0.1-SNAPSHOT.jar
    
  
    